# Generated by Django 3.2.14 on 2022-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('key', models.CharField(max_length=7)),
                ('verify', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
