# Generated by Django 3.2.14 on 2022-07-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_verificationphonenumber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationphonenumber',
            name='verify_type',
            field=models.CharField(choices=[('S', 'signup'), ('R', 'password_reset')], max_length=2, null=True),
        ),
    ]
